version: "3.6"

services: 
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "9000:80"
    volumes: 
      - ./src:/var/www/
      - ~/.ssh:/root/.ssh

  web:
    build: 
      context: ./
      dockerfile: nginx/Dockerfile
    ports: 
      - "8383:80" 
    volumes: 
      - ./src:/var/www
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    links: 
      - php

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
